# Build then discard compiler
FROM rust:1.82-bullseye AS builder

WORKDIR /usr/src/bazingabot
COPY . . 

RUN cargo install --path .

# Production environment
FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/bazingabot /usr/src/bazingabot/.env /usr/local/bin/

CMD cd /usr/local/bin && /usr/local/bin/bazingabot
