name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: "Docker image build & publish"
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.production
          push: true
          cache-from: type=registry,ref=ghcr.io/terisikk/bazingabot:latest
          cache-to: type=inline
          tags: ghcr.io/terisikk/bazingabot:latest
